### ISSUE TITLE
duplicate __describe_after_spec

### ISSUE THREAD

**Issue by tj** [stephenmathieson/describe.h#9]
for my use-case it'd be nice to move __describe_after_spec to a .c, but not a big deal, easy enough local change :D

**Comment by jwerle** [comment]
or a macro!

**Comment by stephenmathieson** [comment]
@jwerle macro in a macro in a macro sounds like hell to debug should we ever need to haha

@tj I'll play around with moving the after_spec into a .c. I've been contemplating a rewrite to support #7 anyway
